{% set name = "docrep" %}
{% set version = "0.2.0" %}
{% set sha256 = "2533fe0c71e1f6049a22e82f7b7471f94baf05a0aed3793a73b04ab8db76c9dc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - six

test:
  imports:
    - docrep

about:
  home: https://github.com/Chilipp/docrep
  license: GPLv2
  license_family: GPL2
  license_file: LICENSE
  summary: 'Python package for docstring repetition'

  description: |
    The documentation repetition module (docrep) targets developpers that
    develop complex and nested Python APIs and helps them to create a
    well-documented software.
  doc_url: http://docrep.readthedocs.io/
  dev_url: https://github.com/Chilipp/docrep

extra:
  recipe-maintainers:
    - Chilipp
