{% set name = "docrep" %}
{% set version = "0.3.0" %}
{% set sha256 = "8e7d87c284df6ed7c8d27e4efb40275dc61bd33d49f19c693092944019f1b922" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - six

test:
  imports:
    - docrep

about:
  home: https://github.com/Chilipp/docrep
  license: GPL-2.0-only
  license_family: GPL2
  license_file: LICENSE
  summary: Python package for docstring repetition

  description: |
    The documentation repetition module (docrep) targets developpers that
    develop complex and nested Python APIs and helps them to create a
    well-documented software.
  doc_url: http://docrep.readthedocs.io/
  dev_url: https://github.com/Chilipp/docrep

extra:
  recipe-maintainers:
    - Chilipp
