travis:
  secure:
    BINSTAR_TOKEN: U7BlG6JLN5STQpiebjpP3OevxIFbhQq38hcAyPz2YHjyjrsPShBPTe9rc/i6xMURTlMRFrcFgOePHvzrV5hx7IdmSCS6OteevlSQBxpzqX40PZXSQAwzNySh6bs9bC+fl5NVjhcfD2IdA80wQpLTRieifpTnJIiFp34SieXaatEMgqjlA9z8P9JXhIpekwJQOfAx4jCkqSJsjckqQv7uhCaDyX25B1Wia+vLeNfsDp2f8JgXe4mf6lfI+Hru4sgjFkN3MLPGERTpsBWkibV5MQc6fVNnErq+w2TH5IrHKzd8OYa+syt5f92v3sQZOFR0Chk3AyHX7CaRUJ+Guenh3rKl5uM9Fn5TCU64n6QRkQYNXYEoZ4anBIX/G8fBUJWpWPcpvTerfzXGV/35AFsXEQYqxF26Tth9OIvgE0B+wa3NeBdL0nrdMu0uYgHI3WJuoUHu2XdQHn/9igUk8ioIOXA1eVyRQvdGL7T8A6nSp5AXpgEM+qRbQkBrH0dTebh5i+RWVhlxaRhEeBuH71XxndW7OIMf/dePLNbznTUeX3xhCbnyi1iqFj6dXLK7Lp+cwbt1OFMHWHppmswVrhO+zhqDhIW5vZbKs9dQsv2B9FryRShq5OSdv73Gt4p1MwVGZPP9yPVt59ImZGWOga35Js5YZVNZ4Sq1f4VMlo21XlQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
