travis:
  secure:
    BINSTAR_TOKEN: SPxRhhkeFWZeixKeb6jOGGE6sEmNBSiYfSSmKyBRBoB8U5N4Sn7UARfBspU4FFzob+luIi5PW1M8Qvh9RJd1fjbwGJB+0xTakmPkDjjGvWvKJRdkAfVXNPbuVI4lj+QzEUu9ilPfZjNIUn9nXaDoEKDab7V4aGWnNVv04MPcWtKpxhuFs2SZN+5byPOyZSO/252PRgvfU2GLEc7+a+ma3XC5EiLQb8yRj6Z7K01CUJjN+AMRhqaoPQBPN22oXkXlaAI9RndfWrjnGSi7FK5H6JGpGZBxzl3q/xLJ3Cn22ud4A1o+8Da5vt3KAf9A5nk8tsw3wRWoHA/KRbQc5oumHFX7V6f067I4k1cHY+jeVFo83pUS3v1rNyJZ/NTU+QZPp6NaItI/gtCl0v8z4KpkT9GkdNuvcIM+cWyPPbByCPjrIb2j7rMWlowVX3qcKyx2DQNjDdwf5VGNuvydI8yDC2+o5kT9XrZIIMIkkr4aqc0gSMJMq3gazJc0Uy88TQcUgy1bM4GqJr2Khf4KcvrhEwHOsiPS7MFExa612El0DGeh4gurAgXvknyfsixNXzTzzsaWckvZvk+wCMmE3vQVO6RsR3MZ2rQHMmojbYgDNl/yyPNNlaJoNGgEkhNjju+NIuSGLyrpL+Jw3T1eehIlj206gABOuoayFVdegIPGBsc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
